"""Self-contained HTML report with interactive plotly charts.

Plotly is loaded from the CDN (`include_plotlyjs="cdn"`) — the file is small
and opens in any browser with internet. Switch to `include_plotlyjs=True` if
you need a fully offline bundle (~3MB heavier).
"""

from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Literal

import pandas as pd
import plotly.express as px
from jinja2 import Template

from flatview.analytics import (
    compute_percentiles,
    compute_stats,
    iqr_fence,
    price_per_m2,
    stats_by_segment,
)
from flatview.models import Listing
from flatview.storage import median_pm2_over_time, query_recent_count

_TEMPLATE = Template(
    """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>flatview — {{ title }}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         margin: 24px; color: #222; max-width: 1200px; }
  h1 { margin-bottom: 4px; }
  .meta { color: #666; margin-bottom: 24px; }
  h2 { border-bottom: 1px solid #eee; padding-bottom: 6px; margin-top: 36px; }
  table { border-collapse: collapse; margin: 12px 0; }
  th, td { padding: 6px 12px; border: 1px solid #ddd; text-align: right; }
  th { background: #f6f6f6; }
  td:first-child, th:first-child { text-align: left; }
  .chart { margin: 16px 0 32px 0; }
  .segment-new { color: #0a7f33; font-weight: 600; }
  .segment-resale { color: #1f6feb; font-weight: 600; }
  .segment-unknown { color: #888; }
  .outlier { background: #fff8e1; }
  .bargain { background: #e8f5e9; }
  .overpriced { background: #ffebee; }
  .small { font-size: 13px; color: #555; }
  a { color: #1f6feb; text-decoration: none; }
  a:hover { text-decoration: underline; }
</style>
</head>
<body>
<h1>flatview report</h1>
<div class="meta">
  {% if query %}Query: <strong>{{ query }}</strong> · {% endif %}
  {% if location %}Location: <strong>{{ location }}</strong> · {% endif %}
  Sources: {{ sources|join(", ") }} · {{ n_total }} listings
  {% if currency %} · prices in {{ currency }}{% endif %}
</div>

{{ stats_html }}

{% for chart in charts %}
<div class="chart">{{ chart }}</div>
{% endfor %}

{% if cma_html %}{{ cma_html }}{% endif %}

{% if outlier_html %}{{ outlier_html }}{% endif %}

{{ comparables_html }}

<p class="small">Generated by flatview. Charts powered by plotly.</p>
</body>
</html>"""
)


def _listings_to_df(listings: list[Listing]) -> pd.DataFrame:
    rows = []
    for l in listings:
        rows.append(
            {
                "title": l.title,
                "source": l.source,
                "segment": l.segment,
                "price": l.price,
                "area": l.area,
                "pm2": price_per_m2(l),
                "city": l.city,
                "url": l.url,
                "is_outlier": l.is_outlier,
                "first_seen": l.first_seen,
                "previous_price": l.previous_price,
            }
        )
    return pd.DataFrame(rows)


def _fmt(v) -> str:
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return "—"
    if isinstance(v, float):
        return f"{v:,.0f}"
    return str(v)


def _stat_table(label: str, stats: dict, currency: str) -> str:
    if not stats or stats.get("n_total") == 0:
        return ""
    price = stats.get("price", {})
    pm2 = stats.get("pm2", {})
    rows = [
        ("Count", price.get("n", 0), pm2.get("n", 0)),
        ("Min", price.get("min"), pm2.get("min")),
        ("P10", price.get("p10"), pm2.get("p10")),
        ("P25", price.get("p25"), pm2.get("p25")),
        ("Median (P50)", price.get("p50"), pm2.get("p50")),
        ("Avg", price.get("avg"), pm2.get("avg")),
        ("P75", price.get("p75"), pm2.get("p75")),
        ("P90", price.get("p90"), pm2.get("p90")),
        ("Max", price.get("max"), pm2.get("max")),
    ]
    body = "\n".join(
        f"<tr><td>{name}</td><td>{_fmt(p)}</td><td>{_fmt(m)}</td></tr>" for name, p, m in rows
    )
    return (
        f"<h3>{label}</h3>"
        f"<table><thead><tr><th>Metric</th>"
        f"<th>Price ({currency})</th><th>{currency}/m²</th></tr></thead>"
        f"<tbody>{body}</tbody></table>"
    )


def _build_stats_section(listings: list[Listing], exclude_outliers: bool) -> str:
    overall = compute_stats(listings, exclude_outliers=exclude_outliers)
    currency = overall.get("currency", "EUR")
    parts = ["<h2>Statistics</h2>"]
    if exclude_outliers:
        parts.append("<p class='small'>Outliers excluded from stats and charts.</p>")
    parts.append(_stat_table("Overall", overall, currency))

    per_seg = stats_by_segment(listings, exclude_outliers=exclude_outliers)
    label_map = {"new": "New build", "resale": "Resale", "unknown": "Unclassified"}
    for seg in ("new", "resale", "unknown"):
        if seg in per_seg:
            parts.append(_stat_table(label_map[seg], per_seg[seg], currency))
    return "\n".join(parts)


def _build_charts(df: pd.DataFrame, exclude_outliers: bool) -> list[str]:
    work = df[~df["is_outlier"]] if exclude_outliers else df
    charts: list[str] = []

    price_df = work[work["price"].notna()]
    if not price_df.empty:
        fig = px.histogram(
            price_df,
            x="price",
            color="segment",
            nbins=30,
            title="Price distribution",
            color_discrete_map={"new": "#0a7f33", "resale": "#1f6feb", "unknown": "#888"},
        )
        charts.append(fig.to_html(full_html=False, include_plotlyjs="cdn"))

    pm2_df = work[work["pm2"].notna()]
    if not pm2_df.empty:
        fig = px.histogram(
            pm2_df,
            x="pm2",
            color="segment",
            nbins=30,
            title="€/m² distribution",
            color_discrete_map={"new": "#0a7f33", "resale": "#1f6feb", "unknown": "#888"},
        )
        charts.append(fig.to_html(full_html=False, include_plotlyjs=False))

    scatter_df = work[work["price"].notna() & work["area"].notna()]
    if not scatter_df.empty:
        fig = px.scatter(
            scatter_df,
            x="area",
            y="price",
            color="segment",
            hover_data=["title", "city", "url"],
            title="Area vs price",
            color_discrete_map={"new": "#0a7f33", "resale": "#1f6feb", "unknown": "#888"},
        )
        charts.append(fig.to_html(full_html=False, include_plotlyjs=False))

    if not pm2_df.empty and pm2_df["source"].nunique() > 1:
        fig = px.box(
            pm2_df,
            x="source",
            y="pm2",
            color="source",
            title="€/m² by source",
            points="outliers",
        )
        charts.append(fig.to_html(full_html=False, include_plotlyjs=False))

    return charts


def _build_history_chart(conn: sqlite3.Connection | None) -> str | None:
    if conn is None:
        return None
    series = median_pm2_over_time(conn)
    if len(series) < 2:
        return None
    df = pd.DataFrame(series, columns=["observed_at", "median_pm2"])
    df["observed_at"] = pd.to_datetime(df["observed_at"])
    fig = px.line(
        df,
        x="observed_at",
        y="median_pm2",
        title="Median €/m² over time (across all stored observations)",
        markers=True,
    )
    return fig.to_html(full_html=False, include_plotlyjs=False)


def _build_outlier_section(listings: list[Listing]) -> str:
    flagged = [l for l in listings if l.is_outlier]
    if not flagged:
        return ""
    fence = iqr_fence(listings)
    fence_str = (
        f"<p class='small'>IQR fence on €/m²: "
        f"<strong>{fence[0]:,.0f}</strong> – <strong>{fence[1]:,.0f}</strong>.</p>"
        if fence
        else ""
    )

    def _table(items: list[Listing], css: str) -> str:
        rows = "\n".join(
            f"<tr class='{css}'><td><a href='{l.url}'>{l.title}</a></td>"
            f"<td>{l.source}</td>"
            f"<td>{_fmt(l.price)}</td><td>{_fmt(l.area)}</td>"
            f"<td>{_fmt(price_per_m2(l))}</td></tr>"
            for l in items
        )
        return (
            f"<table><thead><tr><th>Title</th><th>Source</th>"
            f"<th>Price</th><th>Area</th><th>€/m²</th></tr></thead>"
            f"<tbody>{rows}</tbody></table>"
        )

    bargains = [l for l in flagged if l.outlier_side == "bargain"]
    overpriced = [l for l in flagged if l.outlier_side == "overpriced"]
    other = [l for l in flagged if l.outlier_side is None]

    parts = [f"<h2>Outliers ({len(flagged)})</h2>", fence_str]
    if bargains:
        parts.append(f"<h3>Potential bargains ({len(bargains)}) — below the low fence</h3>")
        parts.append(_table(bargains, "bargain"))
    if overpriced:
        parts.append(f"<h3>Overpriced ({len(overpriced)}) — above the high fence</h3>")
        parts.append(_table(overpriced, "overpriced"))
    if other:
        parts.append(_table(other, "outlier"))
    return "\n".join(parts)


def _build_comparables(listings: list[Listing], n: int = 10) -> str:
    pool = [l for l in listings if not l.is_outlier and price_per_m2(l) is not None]
    if not pool:
        return ""
    pm2s = [pm2 for l in pool if (pm2 := price_per_m2(l)) is not None]
    median = compute_percentiles(pm2s, (50,))[50]
    pool.sort(key=lambda l: abs((price_per_m2(l) or 0) - median))
    top = pool[:n]
    rows = "\n".join(
        f"<tr><td><a href='{l.url}'>{l.title}</a></td><td>{l.source}</td>"
        f"<td><span class='segment-{l.segment}'>{l.segment}</span></td>"
        f"<td>{_fmt(l.price)}</td><td>{_fmt(l.area)}</td>"
        f"<td>{_fmt(price_per_m2(l))}</td></tr>"
        for l in top
    )
    return (
        f"<h2>Top {len(top)} comparables (closest to median €/m²)</h2>"
        f"<p class='small'>Median €/m²: <strong>{median:,.0f}</strong></p>"
        f"<table><thead><tr><th>Title</th><th>Source</th><th>Segment</th>"
        f"<th>Price</th><th>Area</th><th>€/m²</th></tr></thead>"
        f"<tbody>{rows}</tbody></table>"
    )


def _build_cma_view(
    listings: list[Listing],
    target_area: float,
    conn: sqlite3.Connection | None,
) -> str:
    candidates = [
        l for l in listings if l.area is not None and l.price is not None and not l.is_outlier
    ]
    if not candidates:
        return "<h2>CMA</h2><p>No comparable listings available.</p>"

    candidates.sort(key=lambda l: abs((l.area or 0) - target_area))
    top = candidates[:10]

    # Tight band: pull comps within ±25% of target area for the recommendation.
    band = [l for l in top if l.area and abs(l.area - target_area) <= target_area * 0.25]
    band = band or top

    pm2_vals = sorted(pm2 for l in band if (pm2 := price_per_m2(l)) is not None)
    if not pm2_vals:
        return "<h2>CMA</h2><p>No €/m² data among comparables.</p>"

    from flatview.analytics import compute_percentiles

    pcts = compute_percentiles(pm2_vals, (25, 50, 75))
    rec_low = pcts[25] * target_area
    rec_mid = pcts[50] * target_area
    rec_high = pcts[75] * target_area

    velocity_30d = query_recent_count(conn, days=30) if conn is not None else None
    currency = top[0].currency or "EUR"

    rows = "\n".join(
        f"<tr><td><a href='{l.url}'>{l.title}</a></td><td>{l.source}</td>"
        f"<td><span class='segment-{l.segment}'>{l.segment}</span></td>"
        f"<td>{_fmt(l.price)}</td><td>{_fmt(l.area)}</td>"
        f"<td>{_fmt(price_per_m2(l))}</td>"
        f"<td>{_fmt(l.first_seen)}</td></tr>"
        for l in top
    )

    velocity_html = (
        f"<li>Market velocity (last 30 days, all stored listings): "
        f"<strong>{velocity_30d}</strong></li>"
        if velocity_30d is not None
        else ""
    )

    return (
        f"<h2>CMA — target {target_area:.0f} m²</h2>"
        f"<p>Comparable count (within ±25% area): <strong>{len(band)}</strong></p>"
        f"<ul>"
        f"<li>P25 €/m²: <strong>{pcts[25]:,.0f}</strong> "
        f"→ asking ~{rec_low:,.0f} {currency}</li>"
        f"<li>Median €/m²: <strong>{pcts[50]:,.0f}</strong> "
        f"→ asking ~{rec_mid:,.0f} {currency}</li>"
        f"<li>P75 €/m²: <strong>{pcts[75]:,.0f}</strong> "
        f"→ asking ~{rec_high:,.0f} {currency}</li>"
        f"<li>Recommended range: "
        f"<strong>{rec_low:,.0f} – {rec_high:,.0f} {currency}</strong></li>"
        f"{velocity_html}"
        f"</ul>"
        f"<h3>Top comparables by area proximity</h3>"
        f"<table><thead><tr><th>Title</th><th>Source</th><th>Segment</th>"
        f"<th>Price</th><th>Area</th><th>€/m²</th><th>First seen</th></tr></thead>"
        f"<tbody>{rows}</tbody></table>"
    )


def render_report(
    listings: list[Listing],
    *,
    query: str,
    location: str,
    sources: list[str],
    out_path: Path,
    mode: Literal["full", "cma"] = "full",
    cma_target_area: float | None = None,
    history_conn: sqlite3.Connection | None = None,
    exclude_outliers: bool = False,
) -> None:
    df = _listings_to_df(listings)
    overall = compute_stats(listings, exclude_outliers=exclude_outliers)

    charts = _build_charts(df, exclude_outliers)
    hist_chart = _build_history_chart(history_conn)
    if hist_chart:
        charts.append(hist_chart)

    stats_html = _build_stats_section(listings, exclude_outliers)
    outlier_html = _build_outlier_section(listings)
    comparables_html = _build_comparables(listings)

    cma_html = ""
    if mode == "cma" and cma_target_area is not None:
        cma_html = _build_cma_view(listings, cma_target_area, history_conn)

    html = _TEMPLATE.render(
        title=query or "Listings",
        query=query,
        location=location,
        sources=sources,
        n_total=len(listings),
        currency=overall.get("currency", ""),
        stats_html=stats_html,
        charts=charts,
        outlier_html=outlier_html,
        comparables_html=comparables_html,
        cma_html=cma_html,
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html, encoding="utf-8")
